[project]
name = "ml-zoomcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "scikit-learn==1.6.1",
]

[tool.uv.workspace]
members = [
    "hw_05",
    "hw_08",
    "hw_09",
]
