[project]
name = "hw-08"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "numpy>=2.3.4",
    "torch==2.8.0",
    "torchvision>=0.23.0",
]
